# CMake generated Testfile for 
# Source directory: /home/bruno/CodeSpace/slt_cpp_programn
# Build directory: /home/bruno/CodeSpace/slt_cpp_programn/build_linux
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_address "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_address")
set_tests_properties(test_address PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_assessor "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_assessor")
set_tests_properties(test_assessor PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_assessor_manager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_assessor_manager")
set_tests_properties(test_assessor_manager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_automobile_anxiety_inventory "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_automobile_anxiety_inventory")
set_tests_properties(test_automobile_anxiety_inventory PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_beck_anxiety_inventory "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_beck_anxiety_inventory")
set_tests_properties(test_beck_anxiety_inventory PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_beck_depression_inventory "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_beck_depression_inventory")
set_tests_properties(test_beck_depression_inventory PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_case_profile_manager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_case_profile_manager")
set_tests_properties(test_case_profile_manager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_client_manager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_client_manager")
set_tests_properties(test_client_manager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_core_classes "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_core_classes")
set_tests_properties(test_core_classes PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_datetime "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_datetime")
set_tests_properties(test_datetime PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_emergency_contact "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_emergency_contact")
set_tests_properties(test_emergency_contact PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_family_physician "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_family_physician")
set_tests_properties(test_family_physician PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_insurance_company "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_insurance_company")
set_tests_properties(test_insurance_company PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_legal_representative "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_legal_representative")
set_tests_properties(test_legal_representative PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_utils "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_utils")
set_tests_properties(test_utils PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;172;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_PainBodyMap "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_PainBodyMap")
set_tests_properties(test_PainBodyMap PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_ActivitiesOfDailyLiving "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_ActivitiesOfDailyLiving")
set_tests_properties(test_ActivitiesOfDailyLiving PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_SCL90R "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_SCL90R")
set_tests_properties(test_SCL90R PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_BDIManager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_BDIManager")
set_tests_properties(test_BDIManager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_BAIManager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_BAIManager")
set_tests_properties(test_BAIManager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_SCL90RManager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_SCL90RManager")
set_tests_properties(test_SCL90RManager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_AAIManager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_AAIManager")
set_tests_properties(test_AAIManager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_AAIManager_CSVNegative "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_AAIManager_CSVNegative")
set_tests_properties(test_AAIManager_CSVNegative PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;191;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_AddressManager "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_AddressManager")
set_tests_properties(test_AddressManager PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;207;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_pdf "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_pdf")
set_tests_properties(test_pdf PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;214;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_database "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_database")
set_tests_properties(test_database PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;214;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_datetime_integration "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_datetime_integration")
set_tests_properties(test_datetime_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;214;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_pragmas "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_pragmas")
set_tests_properties(test_pragmas PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;214;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
add_test(test_form_generation "/home/bruno/CodeSpace/slt_cpp_programn/build_linux/test_form_generation")
set_tests_properties(test_form_generation PROPERTIES  _BACKTRACE_TRIPLES "/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;214;add_test;/home/bruno/CodeSpace/slt_cpp_programn/CMakeLists.txt;0;")
